In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("C:/Users/Hager/Documents/Final Project/railway.csv")

## Data understanding
* DF shape

* head and tail

* dtypes

* describe

In [4]:
df.shape

(31653, 18)

In [5]:
df.head(20)

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No
5,4e1dcd88-3d95-44ef-99fa,2023-12-30,07:56:06,Online,Credit Card,NaN,Standard,Advance,35,London Kings Cross,York,2024-01-01,06:15:00,08:05:00,08:05:00,On Time,NaN,No
6,1c74479d-85a4-4ba1-a607,2023-12-31,00:02:01,Station,Credit Card,Adult,Standard,Advance,2,London Euston,Oxford,2024-01-01,22:30:00,23:40:00,23:40:00,On Time,NaN,No
7,febf8dab-f808-46fa-bf2b,2023-12-31,01:35:18,Station,Contactless,Disabled,Standard,Advance,2,Liverpool Lime Street,Manchester Piccadilly,2024-01-01,00:00:00,00:30:00,00:30:00,On Time,NaN,No
8,01df916f-4291-41ec-a37d,2023-12-31,01:43:09,Station,Credit Card,NaN,Standard,Advance,37,London Euston,York,2024-01-01,00:00:00,01:50:00,02:07:00,Delayed,Signal Failure,No
9,a8cedba7-1923-459d-b046,2023-12-31,03:05:52,Online,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,01:30:00,02:30:00,02:30:00,On Time,NaN,No
10,b3e5ca7d-e76c-49f2-b49f,2023-12-31,03:26:37,Online,Contactless,NaN,Standard,Advance,8,York,Durham,2024-01-01,01:45:00,02:35:00,02:35:00,On Time,NaN,No
11,6c63f7ac-d590-4356-9eaa,2023-12-31,03:52:11,Online,Contactless,Adult,Standard,Advance,8,London Paddington,Reading,2024-01-01,02:15:00,03:15:00,03:15:00,On Time,NaN,No
12,2e7add75-566a-41aa-9468,2023-12-31,05:55:22,Online,Contactless,NaN,Standard,Advance,3,Manchester Piccadilly,Liverpool Lime Street,2024-01-01,04:15:00,04:45:00,04:45:00,On Time,NaN,No
13,7ed9b545-eb6f-49b2-9b5a,2023-12-31,06:44:35,Online,Contactless,NaN,Standard,Advance,3,Manchester Piccadilly,Liverpool Lime Street,2024-01-01,05:00:00,05:30:00,05:30:00,On Time,NaN,No
14,2e05e2a6-88a8-40fb-bacc,2023-12-31,08:05:50,Online,Credit Card,Disabled,Standard,Advance,15,Birmingham New Street,London St Pancras,2024-01-01,06:30:00,07:50:00,07:50:00,On Time,NaN,No
15,8a18d3b4-995e-49bf-93a3,2023-12-31,08:16:53,Online,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,07:45:00,08:45:00,08:45:00,On Time,NaN,No
16,7493a611-342a-4b17-90dc,2023-12-31,08:23:15,Online,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,07:45:00,08:45:00,08:45:00,On Time,NaN,No
17,054676ac-a976-4909-a26e,2023-12-31,09:09:20,Online,Credit Card,NaN,Standard,Advance,8,London St Pancras,Birmingham New Street,2024-01-01,07:30:00,08:50:00,08:50:00,On Time,NaN,No
18,6b62b452-c491-468d-b39c,2023-12-31,09:12:21,Online,Credit Card,NaN,Standard,Advance,35,London Kings Cross,York,2024-01-01,07:30:00,09:20:00,09:20:00,On Time,NaN,No
19,85e38992-6c6c-4569-914e,2023-12-31,10:42:22,Online,Credit Card,NaN,Standard,Advance,35,London Kings Cross,York,2024-01-01,09:00:00,10:50:00,10:50:00,On Time,NaN,No

In [6]:
df.columns

Index(['Transaction ID', 'Date of Purchase', 'Time of Purchase',
       'Purchase Type', 'Payment Method', 'Railcard', 'Ticket Class',
       'Ticket Type', 'Price', 'Departure Station', 'Arrival Destination',
       'Date of Journey', 'Departure Time', 'Arrival Time',
       'Actual Arrival Time', 'Journey Status', 'Reason for Delay',
       'Refund Request'],
      dtype='object')

In [7]:
df.dtypes

Transaction ID         object
Date of Purchase       object
Time of Purchase       object
Purchase Type          object
Payment Method         object
Railcard               object
Ticket Class           object
Ticket Type            object
Price                   int64
Departure Station      object
Arrival Destination    object
Date of Journey        object
Departure Time         object
Arrival Time           object
Actual Arrival Time    object
Journey Status         object
Reason for Delay       object
Refund Request         object
dtype: object

In [8]:
df.describe()

              Price
count  31653.000000
mean      23.439200
std       29.997628
min        1.000000
25%        5.000000
50%       11.000000
75%       35.000000
max      267.000000

# Data prep
* Fixing dtypes
* Identify and drop duplicates 
* Remove nulls

* Fixing dtypes

In [9]:
print("\nData types before conversion:")

df.dtypes

Data types before conversion:

Transaction ID         object
Date of Purchase       object
Time of Purchase       object
Purchase Type          object
Payment Method         object
Railcard               object
Ticket Class           object
Ticket Type            object
Price                   int64
Departure Station      object
Arrival Destination    object
Date of Journey        object
Departure Time         object
Arrival Time           object
Actual Arrival Time    object
Journey Status         object
Reason for Delay       object
Refund Request         object
dtype: object

In [10]:
#Convert Date
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])
df["Date of Journey"]  = pd.to_datetime(df["Date of Journey"])
print("\nData types after conversion:")
df.dtypes

Data types after conversion:

Transaction ID                 object
Date of Purchase       datetime64[ns]
Time of Purchase               object
Purchase Type                  object
Payment Method                 object
Railcard                       object
Ticket Class                   object
Ticket Type                    object
Price                           int64
Departure Station              object
Arrival Destination            object
Date of Journey        datetime64[ns]
Departure Time                 object
Arrival Time                   object
Actual Arrival Time            object
Journey Status                 object
Reason for Delay               object
Refund Request                 object
dtype: object

* Identify and drop duplicates

In [11]:
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0

* Identifying and Removing nulls

In [12]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

* Cleaning the Null values in each column

In [13]:
# Railcard column -> Whether the passenger is a National Railcard holder (Adult, Senior, or Disabled) or not (None).
df["Railcard"] = df["Railcard"].fillna("No Railcard")

In [14]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard                   0
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

In [15]:
df['Reason for Delay'].unique()

array([nan, 'Signal Failure', 'Technical Issue', 'Weather Conditions',
       'Weather', 'Staffing', 'Staff Shortage', 'Signal failure',
       'Traffic'], dtype=object)

In [16]:
# Unify inconsistent Reason for Delay values
delay_map = {
    "Weather": "Weather Conditions",
    "Signal failure": "Signal Failure",
    "Staffing": "Staff Shortage",
}
df["Reason for Delay"] = df["Reason for Delay"].replace(delay_map)
print("\nReason for Delay after unifying:")
print(df["Reason for Delay"].value_counts())

Reason for Delay after unifying:
Reason for Delay
Weather Conditions    1372
Signal Failure         970
Staff Shortage         809
Technical Issue        707
Traffic                314
Name: count, dtype: int64

In [17]:
# Cleaning the null values from Reason for Delay
df["Reason for Delay"] = df.apply(
    lambda row: "No Delay" if row["Journey Status"] == "On Time" and pd.isnull(row["Reason for Delay"])
    else "Unknown" if pd.isnull(row["Reason for Delay"])
    else row["Reason for Delay"],
    axis=1
)

In [19]:
print(df["Reason for Delay"].value_counts())

Reason for Delay
No Delay              27481
Weather Conditions     1372
Signal Failure          970
Staff Shortage          809
Technical Issue         707
Traffic                 314
Name: count, dtype: int64

In [18]:
df.isnull().sum()

Transaction ID            0
Date of Purchase          0
Time of Purchase          0
Purchase Type             0
Payment Method            0
Railcard                  0
Ticket Class              0
Ticket Type               0
Price                     0
Departure Station         0
Arrival Destination       0
Date of Journey           0
Departure Time            0
Arrival Time              0
Actual Arrival Time    1880
Journey Status            0
Reason for Delay          0
Refund Request            0
dtype: int64

In [20]:
# Actual Arrival Time
df["Actual Arrival Time"] = df.apply(
    lambda row: "Cancelled" if row["Journey Status"] == "Cancelled" and pd.isnull(row["Actual Arrival Time"])
    else "Unknown" if pd.isnull(row["Actual Arrival Time"])
    else row["Actual Arrival Time"],
    axis=1
)

In [21]:
df.isnull().sum()

Transaction ID         0
Date of Purchase       0
Time of Purchase       0
Purchase Type          0
Payment Method         0
Railcard               0
Ticket Class           0
Ticket Type            0
Price                  0
Departure Station      0
Arrival Destination    0
Date of Journey        0
Departure Time         0
Arrival Time           0
Actual Arrival Time    0
Journey Status         0
Reason for Delay       0
Refund Request         0
dtype: int64

In [22]:
df.head(5)

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,No Delay,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,No Railcard,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,No Delay,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,No Railcard,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,No Delay,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,No Railcard,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,No Delay,No